import Home3Team from "@/components/Team/Home3Team";
import Banner6 from "@/components/bannner/Banner6";
import Review6 from "@/components/review/Review6";
import About5 from "@/components/about/About5";
import Service5 from "@/components/services/Service5";
import WhatWeDo5 from "@/components/choose/WhatWeDo5";
import CaseStudy5 from "@/components/caseStudy/CaseStudy5";
import Home3Blog from "@/components/blog/Home3Blog";
import Home3Contact from "@/components/contact/Home3Contact";
import Footer3 from "@/components/footer/Footer3";
import Header4 from "@/components/header/Header4";
import Testimonial4 from "@/components/testimonial/Testimonial4";
import useBodyClass from "@/hooks/useBodyClass";
import Head from "next/head";
import { getAllPosts } from "./api/getPosts";
import imageUrlBuilder from "@sanity/image-url";
import { client } from "../../sanity/lib/client";
import Link from "next/link";

function urlFor(source) {
  return imageUrlBuilder(client).image(source);
}

function Home({ posts }) {
  useBodyClass("home-dark2");

  return (
    <>
      <Head>
        <title>Hundred Dev - Software Development in a Jet Speed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/img/sm-logo.svg" />
      </Head>

      <Header4 />
      <Banner6 />
      <Review6 />
      <About5 />
      <Service5 />
      <WhatWeDo5 />
      <CaseStudy5 />
      <Testimonial4 />
      <Home3Contact />
      <div className="home3-blog-area sec-mar">
        <div className="container">
          <div
            className="row mb-55  wow animate fadeInUp"
            data-wow-delay="200ms"
            data-wow-duration="1500ms"
          >
            <div className="col-lg-12 d-flex justify-content-center">
              <div className="section-title-3 text-center">
                <h2>The Latest Article</h2>
                <p>
                  Services are professional offerings provided by businesses to
                  meet specific needs or solve problems for their customers.
                  Services can range from your budject.
                </p>
              </div>
            </div>
          </div>
          <div className="row justify-content-center g-lg-4 gy-5">
            {/* here */}
            {posts.map((post) => {
              const { _id, title, mainImage, publishedAt, slug } = post;
              return (
                <div
                  key={_id}
                  className="col-lg-4 col-md-6 wow animate fadeInLeft"
                  data-wow-delay="300ms"
                  data-wow-duration="1500ms"
                >
                  <div className="single-blog magnetic-item">
                    <div className="blog-img">
                      <img
                        className="img-fluid"
                        src={urlFor(mainImage).url()}
                        alt=""
                      />
                    </div>
                    <div className="blog-content">
                      <ul className="blog-meta">
                        <li>
                          <Link legacyBehavior href={`/blog/${slug.current}`}>
                            <a>May 20, 2023</a>
                          </Link>
                        </li>
                      </ul>
                      <h4>
                        <Link legacyBehavior href={`/blog/${slug.current}`}>
                          <a>{title} </a>
                        </Link>
                      </h4>
                      <div className="blog-footer">
                        <div className="read-btn">
                          <Link legacyBehavior href={`/blog/${slug.current}`}>
                            <a>
                              Read More
                              <svg
                                width={12}
                                height={12}
                                viewBox="0 0 13 13"
                                fill="none"
                                xmlns="http://www.w3.org/2000/svg"
                              >
                                <path d="M0 1H12M12 1V13M12 1L0.5 12" />
                              </svg>
                            </a>
                          </Link>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
      <Footer3 />
    </>
  );
}
export async function getServerSideProps() {
  const allPosts = await getAllPosts();
  const posts = allPosts.slice(0, 3);

  return {
    props: {
      posts,
    },
  };
}

export default Home;
