import Home3Team from "@/components/Team/Home3Team";
import Banner6 from "@/components/bannner/Banner6";
import Review6 from "@/components/review/Review6";
import About5 from "@/components/about/About5";
import Service5 from "@/components/services/Service5";
import WhatWeDo5 from "@/components/choose/WhatWeDo5";
import CaseStudy5 from "@/components/caseStudy/CaseStudy5";
import Home3Blog from "@/components/blog/Home3Blog";    
import Home3Contact from "@/components/contact/Home3Contact";
import Footer3 from "@/components/footer/Footer3";
import Header4 from "@/components/header/Header4";
import Testimonial4 from "@/components/testimonial/Testimonial4";
import useBodyClass from "@/hooks/useBodyClass";
import Head from "next/head";


export default function Home() {
  useBodyClass("home-dark2");

  return (
    <>
      <Head>
        <title>
        Hundred Dev - Software Development in a Jet Speed
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/img/sm-logo.svg" />
      </Head>

      <Header4 />
      <Banner6 />
      <Review6 />
      <About5 />
      <Service5 />
      <WhatWeDo5 />
      <CaseStudy5/>
      <Testimonial4 />
      <Home3Contact />
      <Home3Blog />
      <Footer3 />
    </>
  );
}
